configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/browserbase%2Fbrowserbase-3d350e6cd04452a1654fdb7a93fa7e8dbbf7706273ae7c21818efce9dcf9bbfe.yml
openapi_spec_hash: 25beffd2761e5414d0cb32f74a969a38
config_hash: b3ca4ec5b02e5333af51ebc2e9fdef1b
